### ISSUE TITLE
Compatibility with brewfile/brew bundle?

### ISSUE THREAD

**Issue by bojanraic** [localsend/homebrew-localsend#2]
Hi,

I am trying to install localsend with brewfile/brew bundle

For a simple Brewfile 
```
tap "localsend/localsend"
brew "localsend"
```
when I run `brew bundle install`, I  am getting 

```bash 
Using localsend/localsend
Installing localsend
Warning: 'localsend' formula is unreadable: No available formula with the name "localsend". Did you mean localtunnel?
Installing localsend formula. It is not currently installed.
Warning: No available formula with the name "localsend". Did you mean localtunnel?
```

I can get it to install imperatively with brew tap `localsend/localsend && brew install localsend`  or `brew install localsend/localsend/localsend` but not via Brewfile/brew bundle

Is there another way to do it or is the tap perhaps incompatible with brewfile/brew bundle?

**Comment by Tienisto** [comment]
Unfortunately, I am not that familiar with homebrew.
But I suspect that's because LocalSend is a "Cask" and not a regular program.

**Comment by bojanraic** [comment]
Thank you for the reply. I can confirm that it works as expected when I change brew directive to cask.
Cheers!
