### ISSUE TITLE
Homebrew main repository

### ISSUE THREAD

**Issue by Kruglianin** [localsend/homebrew-localsend#6]
Hi.
Will this project get into the Homebrew main repository?

**Comment by ZhongRuoyu** [comment]
I did this in Homebrew/homebrew-cask#186552. It's now [available](https://formulae.brew.sh/cask/localsend) and can be installed with `brew install --cask localsend`.

**Comment by Tienisto** [comment]
Nice, thank you @ZhongRuoyu .
I believe this repo can be archived.
